In [17]:
import io
import os
import re
import glob
import pandas as pd
import numpy as np
import trellis
from datetime import datetime
import time
import boto3
import pyarrow
import zipfile
# import datetime

from datalakeutils.connectors.dremio_db import DremioDB
from datalakeutils.analysis.dremio.table import Table
from datalakeutils.analysis.dremio.table import AppendableTable
import pytz
import gzip
import pandas as pd
from pandas.io.json import json_normalize 
import json

now_dt = datetime.now(pytz.timezone('America/Chicago'))
time_now = pd.to_datetime(now_dt).hour

In [18]:
dremio = DremioDB(env_name = 'prod')
correction_data = dremio.execute_df('''
select *
from
(

select 

channel, event, integrations, messageId, originalTimestamp, projectId, receivedAt, sentAt, "timestamp" AS "timestamp", type
,
case 
when 
userId = '5159420101070920' then '5159420101070926'
when
userId = '5159420107947570' then '5159420107947572'
when
userId = '5159420105766890' then '5159420105766891'
when
userId = '5159420104474170' then '5159420104474174'
when
userId = '5159420106816880' then '5159420106816885'
when
userId = '5159420101693130' then '5159420101693131'
when
userId = '5159420107577790' then '5159420107577791'
when
userId = '5159420101693130' then '5159420101693131'
when
userId = '5159420104624870' then '5159420104624877'
when
userId = '5159420100948190' then '5159420100948197'
when
userId = '5159420102994080' then '5159420102994082'
when
userId = '5159420107189190' then '5159420107189191'
when
userId = '5159420101383080' then '5159420101383089'
when
userId = '5159420101412290' then '5159420101412292'
when
userId = '5159420101070920' then '5159420101070926'
when
userId = '5159420107947570' then '5159420107947572'
when
userId = '5159420105766890' then '5159420105766891'
when
userId = '5159420104474170' then '5159420104474174'
when
userId = '5159420106816880' then '5159420106816885'
else
coalesce(cc_account_id,userId) end as userId
, version, writeKey, context_integrations_Appboy, context_integrations_name, context_integrations_version, context_library_name, context_library_version, context_protocols_sourceId, context_traits_email, properties_canvas_id, properties_canvas_name, properties_canvas_step_id, properties_canvas_step_name, properties_canvas_variation_id, properties_canvas_variation_name, properties_dispatch_id, properties_ip_pool, properties_app_id, properties_platform, folder_name, properties_in_control_group, properties_campaign_id, properties_campaign_name, properties_message_variation_id, properties_machine_open, context_device_model, context_device_type, properties_bounce_reason, properties_link_url, properties_subscription_group_id, properties_subscription_status, properties_esp, properties_from_domain, properties_is_drop, properties_user_agent, folder_time_name, properties_message_variation_name, properties_conversion_behavior, properties_conversion_behavior_index, properties_state_change_source

from
(
select 
channel, event, integrations, messageId, originalTimestamp, projectId, receivedAt, sentAt, "timestamp" AS "timestamp", type, B.customer_email, B.cc_account_id,userId, version, writeKey, context_integrations_Appboy, context_integrations_name, context_integrations_version, context_library_name, context_library_version, context_protocols_sourceId, context_traits_email, properties_canvas_id, properties_canvas_name, properties_canvas_step_id, properties_canvas_step_name, properties_canvas_variation_id, properties_canvas_variation_name, properties_dispatch_id, properties_ip_pool, properties_app_id, properties_platform, folder_name, properties_in_control_group, properties_campaign_id, properties_campaign_name, properties_message_variation_id, properties_machine_open, context_device_model, context_device_type, properties_bounce_reason, properties_link_url, properties_subscription_group_id, properties_subscription_status, properties_esp, properties_from_domain, properties_is_drop, properties_user_agent, folder_time_name, properties_message_variation_name, properties_conversion_behavior, properties_conversion_behavior_index, properties_state_change_source, B.customer_id
from
(
SELECT SUBSTR(userId,1,15) as cca_key,* FROM "avantcamp-partner01-prod"."avantcamp-partner01-prod-publish-bucket".avant.garden."segment-logs"
where folder_name in
(
1668297600000,
1669248000000,
1668038400000,
1668211200000,
1667865600000,
1669680000000,
1668729600000,
1668902400000,
1668988800000,
1669420800000,
1667952000000,
1669852800000,
1669593600000,
1669161600000,
1668470400000,
1669766400000,
1669334400000,
1668556800000,
1668384000000,
1668816000000,
1668124800000,
1669507200000,
1668643200000,
1669075200000)


) A

left join

(
select SUBSTR(cca.cc_account_id,1,15) as cca_key,cca.cc_account_id,cca.customer_id,customer_email
from 
avant.prod.dw.dw_serv.cc_account cca
left join
avant.prod.dw.dw_serv.customer c
on
c.customer_id = cca.customer_id
) B
on 
A.context_traits_email = B.customer_email
and
A.cca_key = B.cca_key
)

)
''')


for ia in correction_data.folder_name.unique():
    print(ia)
    print(len(correction_data.loc[correction_data.folder_name == ia]))
#     correction_data.drop(['__index_level_0__'],inplace = True)
    correction_data.loc[correction_data.folder_name == ia].to_parquet('{}.parquet'.format(ia))

1669075200000
6533
1669852800000
6181
1668038400000
3371
1668902400000
995
1669680000000
1764
1669766400000
1565
1668816000000
1119
1667952000000
2556
1669593600000
3255
1669334400000
1417
1669248000000
1596
1668384000000
1737
1668124800000
5208
1669507200000
1022
1668729600000
1625
1668643200000
2295
1668988800000
11258
1668297600000
1202
1668211200000
1759
1668556800000
8004
1669161600000
1976
1669420800000
1156
1667865600000
2951
1668470400000
1750

In [ ]:
a

In [6]:
a = pd.concat(appended_data)

In [11]:
a[["cc_account_id","userId"]]

       cc_account_id            userId
0   5159420104033731  5159420104033730
1   5159420104033731  5159420104033730
2   5159420104033731  5159420104033730
3   5159420104033731  5159420104033730
4   5159420104033731  5159420104033730
..               ...               ...
5   5159420101517173  5159420101517170
6   5159420101517173  5159420101517170
7   5159420101517173  5159420101517170
8   5159420101517173  5159420101517170
9   5159420101517173  5159420101517170

[121430 rows x 2 columns]

In [88]:
for i in data.userId :
    final_data = pd.merge(data[data.userId == "{}".format(i)],correction_data[["cc_account_id","userId"]],left_on = "userId",right_on = "userId",how = "inner")

KeyboardInterrupt:

In [107]:
final_data = pd.merge(data[data.userId == "5159420100713880".format(i)],correction_data[["cc_account_id","userId"]],left_on = "userId",right_on = "userId",how = "left")

In [108]:
len(data[data.userId == "5159420100713880".format(i)])

2

In [112]:
appended_data = []

In [113]:
appended_data.append(final_data)

In [115]:
pd.concat(appended_data)

,channel,event,integrations,messageId,originalTimestamp,projectId,receivedAt,sentAt,timestamp,type,...,context_device_type,properties_subscription_group_id,properties_subscription_status,properties_user_agent,properties_bounce_reason,properties_conversion_behavior,properties_conversion_behavior_index,folder_time_name,__index_level_0__,cc_account_id
0,server,Email Opened,{},f0f43ea7-7022-4f80-ba63-e94ac7f606fb,2022-11-17T00:06:13Z,gAM2my4ZrptM2qXHJts882,2022-11-17T00:06:25.996Z,nan,2022-11-17 00:06:13,track,...,nan,nan,nan,Mozilla/5.0,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,0,5159420100713880
1,server,Email Opened,{},985a16ef-29ec-48f7-bbe5-0f52e65d53ae,2022-11-17T00:06:12Z,gAM2my4ZrptM2qXHJts882,2022-11-17T00:06:25.934Z,nan,2022-11-17 00:06:12,track,...,nan,nan,nan,lua-resty-http/0.10 (Lua) ngx_lua/10019,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,0,5159420100713880

In [97]:
final_data.cc_account_id[0]

'5159420100713880'

In [84]:
final_data.drop(columns = ['userId'],inplace = True)
final_data.rename(

,channel,event,integrations,messageId,originalTimestamp,projectId,receivedAt,sentAt,timestamp,type,...,properties_subscription_status,properties_user_agent,properties_bounce_reason,properties_conversion_behavior,properties_conversion_behavior_index,folder_time_name,__index_level_0__,folder_name_y,cc_account_id,context_traits_email_y
0,server,Campaign Converted,{},421eaf62-1965-446a-9c1a-aa2ad69642b6,2022-11-17T05:45:35Z,gAM2my4ZrptM2qXHJts882,2022-11-17T05:45:48.520Z,nan,2022-11-17 05:45:35,track,...,nan,nan,nan,"{""window"":1209600,""type"":""Opens Email""}",0.0,braze_currents_2022-11-17 00:00:00_1668643200000,1,1668643200000,5159420108060516,bigbobelmore@hotmail.com
1,server,Campaign Converted,{},421eaf62-1965-446a-9c1a-aa2ad69642b6,2022-11-17T05:45:35Z,gAM2my4ZrptM2qXHJts882,2022-11-17T05:45:48.520Z,nan,2022-11-17 05:45:35,track,...,nan,nan,nan,"{""window"":1209600,""type"":""Opens Email""}",0.0,braze_currents_2022-11-17 00:00:00_1668643200000,1,1668556800000,5159420108060516,bigbobelmore@hotmail.com
2,server,Email Opened,{},7e32f62f-e7d2-4914-bf49-0e75fb00cabe,2022-11-17T05:45:35Z,gAM2my4ZrptM2qXHJts882,2022-11-17T05:45:47.836Z,nan,2022-11-17 05:45:35,track,...,nan,Mozilla/5.0,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,1,1668643200000,5159420108060516,bigbobelmore@hotmail.com
3,server,Email Opened,{},7e32f62f-e7d2-4914-bf49-0e75fb00cabe,2022-11-17T05:45:35Z,gAM2my4ZrptM2qXHJts882,2022-11-17T05:45:47.836Z,nan,2022-11-17 05:45:35,track,...,nan,Mozilla/5.0,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,1,1668556800000,5159420108060516,bigbobelmore@hotmail.com

In [28]:
ia = 1668643200000
data = dremio.execute_df('''
select 
*
from 
"avantcamp-partner01-prod"."avantcamp-partner01-prod-publish-bucket".avant.garden."segment-logs"."{}.parquet" A

'''.format(ia))

In [39]:
data[data.userId == "5159420100713880"].context_traits_email

0     kris_krebs@westtool.com
48    kris_krebs@westtool.com
Name: context_traits_email, dtype: object

In [31]:
# data.userId

dremio.execute_df('''select 
                    C.customer_uuid
                    from 
                    avant.prod.dw.dw_serv.cc_account A
                    inner join 
                    avant.prod.dw.dw_serv.customer C
                    on
                    A.customer_id = C.customer_id
                    where cc_account_id = 5159420100713880''')

                          customer_uuid
0  d69305ce-7552-4881-af55-d7f9d0cafb0e

In [49]:
data[data.userId == "{}".format(i)].userId

0     5159420100713880
48    5159420100713880
Name: userId, dtype: object

In [106]:
correction_data = correction_data[["cc_account_id","userId"]].drop_duplicates()

In [67]:
correction_data[correction_data.cc_account_id == "5159420100713880"]

         cc_account_id            userId
5608  5159420100713880  5159420100713880

In [66]:
i = "5159420100713880"
pd.merge(data[data.userId == "{}".format(i)],correction_data,left_on = "userId",right_on = "userId",how = "inner")

,channel,event,integrations,messageId,originalTimestamp,projectId,receivedAt,sentAt,timestamp,type,...,context_device_type,properties_subscription_group_id,properties_subscription_status,properties_user_agent,properties_bounce_reason,properties_conversion_behavior,properties_conversion_behavior_index,folder_time_name,__index_level_0__,cc_account_id
0,server,Email Opened,{},f0f43ea7-7022-4f80-ba63-e94ac7f606fb,2022-11-17T00:06:13Z,gAM2my4ZrptM2qXHJts882,2022-11-17T00:06:25.996Z,nan,2022-11-17 00:06:13,track,...,nan,nan,nan,Mozilla/5.0,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,0,5159420100713880
1,server,Email Opened,{},985a16ef-29ec-48f7-bbe5-0f52e65d53ae,2022-11-17T00:06:12Z,gAM2my4ZrptM2qXHJts882,2022-11-17T00:06:25.934Z,nan,2022-11-17 00:06:12,track,...,nan,nan,nan,lua-resty-http/0.10 (Lua) ngx_lua/10019,nan,nan,nan,braze_currents_2022-11-17 00:00:00_1668643200000,0,5159420100713880

In [6]:
for i in correction_data.folder_name.unique():
    print(i)

1668643200000
1668038400000
1669075200000
1668211200000
1668556800000
1668988800000
1668902400000
1667865600000
1669334400000
1669161600000
1669248000000
1667952000000
1668124800000
1669420800000
1669766400000
1668297600000
1668729600000
1669593600000
1668816000000
1668384000000
1669680000000
1669507200000
1668470400000

In [12]:
ia = "1668643200000"
data = dremio.execute_df('''
select 
*,B.cc_account_id
from 
"avantcamp-partner01-prod"."avantcamp-partner01-prod-publish-bucket".avant.garden."segment-logs"."{}.parquet" A
left join
avant.prod.dw."dw_mktg"."ad_hoc"."braze_correction_data" B
on 

A.userId = B.userId


'''.format(ia))

In [25]:
for i in data[["cc_account_id","userId"]][data.cc_account_id.isna()].userId :
    print(i)

23306477-aca1-4db9-bcf2-8f495efe96b1
23306477-aca1-4db9-bcf2-8f495efe96b1
23306477-aca1-4db9-bcf2-8f495efe96b1
23306477-aca1-4db9-bcf2-8f495efe96b1
3993e19c-df39-4efa-99b5-0977613fab1f
5159420109236030
5159420109236030
5159420107879970
88f08ac2-858f-4fa9-a6db-d3b75037dd96
5159420107583300
88a9a40b-49df-4cac-a49c-2736cfeea347
5159420109068370
5159420108709190
dc6d2475-1fd3-491f-8714-87584ac42855
5159420104416290
30b56675-9492-4ae6-a1e1-542ac17f8636
5159420110444770
5159420110444770
5159420105425630
5159420110372430
5159420107751310
5159420100489770
31cdae29-de87-4b08-9c7a-07d281c6d353
41cfcf36-b4b6-47bf-a919-2085e01318c8
41cfcf36-b4b6-47bf-a919-2085e01318c8
902145bd-f6e2-47be-a2f4-d4743cbcf4b4
902145bd-f6e2-47be-a2f4-d4743cbcf4b4
ff372a62-b386-43ad-af78-72b6d6607fa8
ff372a62-b386-43ad-af78-72b6d6607fa8
ff372a62-b386-43ad-af78-72b6d6607fa8
3bb68d2d-9849-4a34-80c8-9e0a05661f8f
3bb68d2d-9849-4a34-80c8-9e0a05661f8f
e0133208-1ac5-483c-8541-f6a814573355
e0133208-1ac5-483c-8541-f6a814573355
696bcce1-f87a-4ca3-9e3f-de92e3a496ba
696bcce1-f87a-4ca3-9e3f-de92e3a496ba
6a587b26-dfc7-4bff-9b44-b9d8ea4dcc71
6a587b26-dfc7-4bff-9b44-b9d8ea4dcc71
122e103d-e1b7-4869-b0da-d62f006e40a0
122e103d-e1b7-4869-b0da-d62f006e40a0
122e103d-e1b7-4869-b0da-d62f006e40a0
a0bef344-9392-4120-b586-a6dbf4cf136b
a0bef344-9392-4120-b586-a6dbf4cf136b
a0bef344-9392-4120-b586-a6dbf4cf136b
a0bef344-9392-4120-b586-a6dbf4cf136b
28b32b6e-8694-4cff-948e-4d02b08c7910
28b32b6e-8694-4cff-948e-4d02b08c7910
179b5a74-c027-4d86-8a09-5bc14978a1e0
179b5a74-c027-4d86-8a09-5bc14978a1e0
ee46dce1-0005-44a6-8e8a-ac79c01e743f
ee46dce1-0005-44a6-8e8a-ac79c01e743f
ee46dce1-0005-44a6-8e8a-ac79c01e743f
ee46dce1-0005-44a6-8e8a-ac79c01e743f
ee46dce1-0005-44a6-8e8a-ac79c01e743f
dfaf64c5-2e09-4ead-9571-ff26b8fd5de9
dfaf64c5-2e09-4ead-9571-ff26b8fd5de9
dfaf64c5-2e09-4ead-9571-ff26b8fd5de9
31dcec0b-34f6-49d4-9730-331feb57fd19
31dcec0b-34f6-49d4-9730-331feb57fd19
487d837b-d9ef-4474-b5cc-00fbc492d475
487d837b-d9ef-4474-b5cc-00fbc492d475
487d837b-d9ef-4474-b5cc-00fbc492d475
bf0ba32e-73a9-4a95-9315-ca5f6e8d8b8d
bf0ba32e-73a9-4a95-9315-ca5f6e8d8b8d
5a705efe-1777-11e3-9b9d-ee614910790c
5a705efe-1777-11e3-9b9d-ee614910790c
e9dbe946-8178-483c-bda8-ac8dc1645d80
e9dbe946-8178-483c-bda8-ac8dc1645d80
e9dbe946-8178-483c-bda8-ac8dc1645d80
e9dbe946-8178-483c-bda8-ac8dc1645d80
e9dbe946-8178-483c-bda8-ac8dc1645d80
a0899ef2-b439-42ba-90e1-6e90cf5add21
a0899ef2-b439-42ba-90e1-6e90cf5add21
ca5e1c0b-36c4-4dff-89ce-afddb46f6b69
ca5e1c0b-36c4-4dff-89ce-afddb46f6b69
ca5e1c0b-36c4-4dff-89ce-afddb46f6b69
8da222a1-1889-40bc-b764-ee2ea048f3fc
8da222a1-1889-40bc-b764-ee2ea048f3fc
27a9535d-c283-4478-9ef3-8887438240db
27a9535d-c283-4478-9ef3-8887438240db
27a9535d-c283-4478-9ef3-8887438240db
bddffbb8-1436-4344-9d25-939c06e245bb
bddffbb8-1436-4344-9d25-939c06e245bb
cae9f27a-5dad-4e58-8d32-6f47a9f7804e
cae9f27a-5dad-4e58-8d32-6f47a9f7804e
2592f414-580a-42e9-b22b-98d47401cb10
2592f414-580a-42e9-b22b-98d47401cb10
2592f414-580a-42e9-b22b-98d47401cb10
a8d2a395-c0de-450e-96d2-843f79cd103d
a8d2a395-c0de-450e-96d2-843f79cd103d
c062d085-5f3f-4657-8c3b-dabba76e27c4
c062d085-5f3f-4657-8c3b-dabba76e27c4
9501736e-93c9-4227-bade-6fed5b606383
9501736e-93c9-4227-bade-6fed5b606383
9501736e-93c9-4227-bade-6fed5b606383
a5b09a5a-f708-495d-9bf8-fc5ee99641ca
a5b09a5a-f708-495d-9bf8-fc5ee99641ca
9a22baec-6007-4f64-a293-2e40f3da105c
9a22baec-6007-4f64-a293-2e40f3da105c
0c21e4c0-6160-437d-b73e-9eec5b82df6c
0c21e4c0-6160-437d-b73e-9eec5b82df6c
0c21e4c0-6160-437d-b73e-9eec5b82df6c
5159420112504980
5159420105844990
2fb58893-12de-46cc-b5ce-789afb307ee6
5159420111430550
5159420102333830
5159420102333830
5159420109290220
fd95d6d3-7735-4d2f-9929-851519eb1899
fd95d6d3-7735-4d2f-9929-851519eb1899
a2710ae2-952f-43d5-9190-51bfba9532b1
5159420106126850
217bc51f-0ff8-40e7-831c-3dbaab10ee04
5159420108155280
f70e5f55-b1b9-4ea3-b25b-efab21f17596
f70e5f55-b1b9-4ea3-b25b-efab21f17596
f70e5f55-b1b9-4ea3-b25b-efab21f17596
5566af43-3a3a-4e42-a90e-c3c22c9d2547
5159420103480210
bdfe89f4-547a-4a8c-a3eb-8669bbc0713b
5159420103469080
5159420102703840
5159420110974570
5159420110974570
f70093cf-042e-469b-97f0-2e558f7ef0d6
c709fafe-cf4d-4335-aa00-14b6afcae545
5159420105361000
5159420101910650
986d3dbf-0541-4af0-a13a-48ff161db06e
5159420105192940
2db19073-9b6e-429a-b018-30623f613681
5159420101635720
7dfce8ff-b81c-4614-ae60-4b5b7eaa3e2c
5159420109444540
5159420109444540
a033906f-54e9-4905-ae13-6bb0a3a55fb2
2e93bdd7-cf12-4f2d-b013-a7f18b5d1151
5159420110629350
e99b4433-1a93-4633-b087-498fc05ec625
e99b4433-1a93-4633-b087-498fc05ec625
435cedeb-c270-4e06-b2a3-e4eb45996f68
435cedeb-c270-4e06-b2a3-e4eb45996f68
435cedeb-c270-4e06-b2a3-e4eb45996f68
14aabaea-0997-4c30-a96e-374e6039d416
14aabaea-0997-4c30-a96e-374e6039d416
e44cad87-4e68-4c93-a5c2-231d87f6c284
e44cad87-4e68-4c93-a5c2-231d87f6c284
e44cad87-4e68-4c93-a5c2-231d87f6c284
30e1c888-7fc3-4f04-8dbd-00587c68961a
30e1c888-7fc3-4f04-8dbd-00587c68961a
30e1c888-7fc3-4f04-8dbd-00587c68961a
5159420111840490
b4802ed2-1a4a-4035-8fbe-ef94f4f366d6
b4802ed2-1a4a-4035-8fbe-ef94f4f366d6
b4802ed2-1a4a-4035-8fbe-ef94f4f366d6
b4802ed2-1a4a-4035-8fbe-ef94f4f366d6
f82b0034-fd31-43a1-9482-d1e2209f1b20
f82b0034-fd31-43a1-9482-d1e2209f1b20
f82b0034-fd31-43a1-9482-d1e2209f1b20
f82b0034-fd31-43a1-9482-d1e2209f1b20
ae30cee9-d3f8-499f-bc03-ef183f43324e
ae30cee9-d3f8-499f-bc03-ef183f43324e
ae30cee9-d3f8-499f-bc03-ef183f43324e
fd97efb0-e7ef-46d0-a36e-86f1f7339fcf
fd97efb0-e7ef-46d0-a36e-86f1f7339fcf
b8c38f85-1ee9-4261-ace3-b9094699fbc0
b8c38f85-1ee9-4261-ace3-b9094699fbc0
b8c38f85-1ee9-4261-ace3-b9094699fbc0
b8c38f85-1ee9-4261-ace3-b9094699fbc0
b8c38f85-1ee9-4261-ace3-b9094699fbc0
5159420111830780
e03fe7da-327c-4490-a332-ec05d35d29aa
e03fe7da-327c-4490-a332-ec05d35d29aa
cd8af479-f06e-4899-9202-e0c354d953f2
cd8af479-f06e-4899-9202-e0c354d953f2
cd8af479-f06e-4899-9202-e0c354d953f2
9b49892d-d256-4472-98bd-b6dc2f560458
9b49892d-d256-4472-98bd-b6dc2f560458
02c5ae6f-115c-4b1c-8d37-2b74ab7f5adf
02c5ae6f-115c-4b1c-8d37-2b74ab7f5adf
914cb3d2-8015-4e8a-963b-ea4a9fff95ba
914cb3d2-8015-4e8a-963b-ea4a9fff95ba
3f166355-78ab-4382-8659-fd8a2a96c6b1
3f166355-78ab-4382-8659-fd8a2a96c6b1
805a83cb-cec0-4eea-8b17-b2839f9e3650
805a83cb-cec0-4eea-8b17-b2839f9e3650
805a83cb-cec0-4eea-8b17-b2839f9e3650
28cb45b0-3c3c-489d-8b08-1a4726243409
28cb45b0-3c3c-489d-8b08-1a4726243409
28cb45b0-3c3c-489d-8b08-1a4726243409
cb67b74a-5475-45f5-bd7d-86bac2f0c3b8
cb67b74a-5475-45f5-bd7d-86bac2f0c3b8
8c392f00-0799-4a8b-af43-0becac337249
8c392f00-0799-4a8b-af43-0becac337249
9b73d610-2608-4d79-a354-59a93a45439c
9b73d610-2608-4d79-a354-59a93a45439c
7a64816e-c3c7-4632-afe9-e0509991b9d6
7a64816e-c3c7-4632-afe9-e0509991b9d6
7a64816e-c3c7-4632-afe9-e0509991b9d6
131b3241-9da1-413d-892f-870bc18d538f
131b3241-9da1-413d-892f-870bc18d538f
131b3241-9da1-413d-892f-870bc18d538f
131b3241-9da1-413d-892f-870bc18d538f
5159420102441010
5159420104005230
5159420104005230
5159420111479210
5159420105468030
5159420103613850
5159420102397690
5159420102397690
5159420101110540
bad80ace-ba6c-4254-8bb6-c164dc07e95b
6e2346ed-2519-457f-ab55-fe8ec2b580dd
6e2346ed-2519-457f-ab55-fe8ec2b580dd
6e2346ed-2519-457f-ab55-fe8ec2b580dd
6b6f03cc-84d1-4339-89ae-f87035cfa7c9
5159420110275150
91411d59-7938-46c2-a50b-48821e129467
5159420111516390
5159420103888410
5159420105009550
3f527d27-cc89-45cf-810c-7679024dc91f
482b91b5-6457-4b52-97c9-3fe36fdc6208
65c88c18-1427-4c15-bc7d-959032b03448
5159420100146710
5159420104972880
5159420101896520
5159420108430070
03579ac6-9bac-45ae-8109-13d6ba353619
23e3b4ca-4a01-499a-949f-430d393979e5
5159420106822180
a13c081a-066e-452f-8da8-3a6fdf3afbed
bbe970be-3836-43f6-80cc-81b95dfb4af2
d78d7195-11b7-4b83-bcb0-63ff07923bb7
65e97c19-f11f-4793-8254-e5a3e7c7f6ae
65e97c19-f11f-4793-8254-e5a3e7c7f6ae
65e97c19-f11f-4793-8254-e5a3e7c7f6ae
b3da250f-cc56-4850-9c40-7f5e73a0d37c
b3da250f-cc56-4850-9c40-7f5e73a0d37c
a6a3fd8f-57e1-45b7-a7e3-0f26bc50b67e
a6a3fd8f-57e1-45b7-a7e3-0f26bc50b67e
b5735b1b-4325-483d-a2cc-d2f70a337841
b5735b1b-4325-483d-a2cc-d2f70a337841
0a210ba4-fe7a-4801-8083-1fd824da9fa1
0a210ba4-fe7a-4801-8083-1fd824da9fa1
0a210ba4-fe7a-4801-8083-1fd824da9fa1
9827724f-ea7c-474b-bf31-c8abec4b1ad9
9827724f-ea7c-474b-bf31-c8abec4b1ad9
6726354e-7ece-4dae-8cab-2645d8608424
6726354e-7ece-4dae-8cab-2645d8608424
6726354e-7ece-4dae-8cab-2645d8608424
6726354e-7ece-4dae-8cab-2645d8608424
d232065e-813c-4594-a709-9f29a9932b27
d232065e-813c-4594-a709-9f29a9932b27
d232065e-813c-4594-a709-9f29a9932b27
d232065e-813c-4594-a709-9f29a9932b27
db6320a0-1a2c-401b-a221-7e15d48b5c77
db6320a0-1a2c-401b-a221-7e15d48b5c77
7ccb8893-532b-43e3-afe1-a993a8bcd31a
7ccb8893-532b-43e3-afe1-a993a8bcd31a
7ccb8893-532b-43e3-afe1-a993a8bcd31a
e78a8df2-1283-42ca-91f2-35acb8dc9366
e78a8df2-1283-42ca-91f2-35acb8dc9366
dff43d6a-d58b-4ea8-bd27-da5a06a57542
dff43d6a-d58b-4ea8-bd27-da5a06a57542
cae4c67f-1ff3-4c65-9604-488651834cb4
cae4c67f-1ff3-4c65-9604-488651834cb4
cae4c67f-1ff3-4c65-9604-488651834cb4
199e94c6-e5b8-11e3-b112-3a94d58cd66d
199e94c6-e5b8-11e3-b112-3a94d58cd66d
b4b57503-03b7-4a9e-909c-6c697d10be47
b4b57503-03b7-4a9e-909c-6c697d10be47
9378b0f1-d706-4767-b4da-bb0d947f7b6a
9378b0f1-d706-4767-b4da-bb0d947f7b6a
7cad23bd-afe4-4d72-8b5e-4cbca43ea4c6
7cad23bd-afe4-4d72-8b5e-4cbca43ea4c6
1e773516-4fd3-409e-8784-c018e3554e63
1e773516-4fd3-409e-8784-c018e3554e63
1e773516-4fd3-409e-8784-c018e3554e63
767b3a30-f2c5-453d-95b6-54e19bcbabe5
767b3a30-f2c5-453d-95b6-54e19bcbabe5
767b3a30-f2c5-453d-95b6-54e19bcbabe5
767b3a30-f2c5-453d-95b6-54e19bcbabe5
767b3a30-f2c5-453d-95b6-54e19bcbabe5
b6b25de7-4baf-4645-b379-135609b8bba7
b6b25de7-4baf-4645-b379-135609b8bba7
ea3c5030-6175-486d-90a2-5a1eb20ea09a
ea3c5030-6175-486d-90a2-5a1eb20ea09a
7d2eb3ab-3d3a-4893-8e80-bf0514e0f868
7d2eb3ab-3d3a-4893-8e80-bf0514e0f868
5159420110696780
4688b9bc-3d11-11e3-a0fe-12e07c7d272c
fb8fa65d-0f06-4d67-8717-646a0d909b5d
fb8fa65d-0f06-4d67-8717-646a0d909b5d
1883e68b-4547-44ab-98d5-1c4b63381172
1883e68b-4547-44ab-98d5-1c4b63381172
539a6ffb-9a32-4396-a479-7e66bf54fdc6
539a6ffb-9a32-4396-a479-7e66bf54fdc6
539a6ffb-9a32-4396-a479-7e66bf54fdc6
5159420106892030
602bc79a-e889-494e-93fc-65fef085b71c
5159420109315160
dbf54b85-09ba-40e9-b1bd-4e6e3d9fd16b
5159420108353720
1ae38f0c-79e0-4c77-a6b9-3312512726b0
a2bf55f9-bfd6-404d-a5a1-a847cbaf6c4d
5159420104015120
3a4cd58e-0708-4a7c-8289-489041720b93
5159420103723190
5159420101434150
9472e2be-01d9-4995-a4e6-acdf5e84e8f6
d73effc8-2fed-4c93-b803-44ddc0a1fa4d
60e2b813-63cb-4758-b9d7-3951bbadfc96
60e2b813-63cb-4758-b9d7-3951bbadfc96
60e2b813-63cb-4758-b9d7-3951bbadfc96
5159420108791410
5159420108791410
31a9791c-0f03-486b-9e5d-673632373990
5159420106218380
3faf68c4-6c3f-4ca7-b54a-45e3bd9764bd
72dd3dbf-a0d7-4443-811d-019b6e79273e
5fb929b6-42cd-4ab4-86ef-12473a1d366d
38bdaacb-bf36-49f6-8137-91d10cef3436
5159420110285990
5159420106998160
5159420109747660
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
5159420111605950
44c16e95-2d9d-49ff-bebc-d8ee60f13acf
6e59ffd5-d34d-45bc-bc72-5419ba0acff4
158a2edf-b24d-4338-8462-ffe76cb0349f
ff781483-37a9-4c7e-a615-2443426d6b6d
6385a5e0-9919-41f7-8faa-50f36f73e5d0
6385a5e0-9919-41f7-8faa-50f36f73e5d0
5159420106051030
fe4c46cd-fe84-424a-b9ce-6eae81a21a9b
fe4c46cd-fe84-424a-b9ce-6eae81a21a9b
fe4c46cd-fe84-424a-b9ce-6eae81a21a9b
7f4f3f66-af49-4b1c-b8d5-6630a1d0c249
7f4f3f66-af49-4b1c-b8d5-6630a1d0c249
bb610461-7030-4263-82e7-ea55dcd17870
bb610461-7030-4263-82e7-ea55dcd17870
e3a1ec9b-758b-4b8b-a747-b2764ee33fa4
e3a1ec9b-758b-4b8b-a747-b2764ee33fa4
e3a1ec9b-758b-4b8b-a747-b2764ee33fa4
efb20fb9-c38c-4013-8a48-b1281a4f46d3
efb20fb9-c38c-4013-8a48-b1281a4f46d3
76ea10a5-1fae-4e53-9805-63c65af788ee
76ea10a5-1fae-4e53-9805-63c65af788ee
4aba5016-1949-4329-824a-0779bf5d6ac7
4aba5016-1949-4329-824a-0779bf5d6ac7
70210644-4ac5-4967-a36d-4da43e546b46
70210644-4ac5-4967-a36d-4da43e546b46
70210644-4ac5-4967-a36d-4da43e546b46
f8a35382-00ca-41ed-9496-3419fef405e2
f8a35382-00ca-41ed-9496-3419fef405e2
f8a35382-00ca-41ed-9496-3419fef405e2
1b9ee6ee-ed26-444a-928e-998ee6ebce48
1b9ee6ee-ed26-444a-928e-998ee6ebce48
8665dc71-4c86-4c46-870d-f21b4f3f7f62
8665dc71-4c86-4c46-870d-f21b4f3f7f62
346a5686-1d09-4eba-a123-7e22da331899
346a5686-1d09-4eba-a123-7e22da331899
94ae1a97-f9a9-4ac9-9c80-bcc7978d9a1d
94ae1a97-f9a9-4ac9-9c80-bcc7978d9a1d
cf84bda5-e02a-4b92-862d-bcc58ec966b4
cf84bda5-e02a-4b92-862d-bcc58ec966b4
cf84bda5-e02a-4b92-862d-bcc58ec966b4
cf84bda5-e02a-4b92-862d-bcc58ec966b4
ccf2254d-e696-44ed-8ce3-7b2dc168a6ff
ccf2254d-e696-44ed-8ce3-7b2dc168a6ff
65c7bc7f-4064-4bb6-9157-0ce3ce7663da
65c7bc7f-4064-4bb6-9157-0ce3ce7663da
b949f4ec-10d4-440e-8734-6917b6299062
b949f4ec-10d4-440e-8734-6917b6299062
6b85bcd4-f6d1-4994-aa7e-0a4af6a25a03
6b85bcd4-f6d1-4994-aa7e-0a4af6a25a03
5159420103626660
51b2701e-41a3-4139-9beb-53b9c908635d
51b2701e-41a3-4139-9beb-53b9c908635d
fd0198c2-f73f-4584-a6a7-6fdc9c4b49b5
fd0198c2-f73f-4584-a6a7-6fdc9c4b49b5
fd0198c2-f73f-4584-a6a7-6fdc9c4b49b5
fd0198c2-f73f-4584-a6a7-6fdc9c4b49b5
7162426f-685b-4981-aebd-9ad9a8d0472a
7162426f-685b-4981-aebd-9ad9a8d0472a
4d625006-2ea6-4b93-b0c2-68ef22ec18db
4d625006-2ea6-4b93-b0c2-68ef22ec18db
4d625006-2ea6-4b93-b0c2-68ef22ec18db
5159420109478330
ed868d6c-0ade-4728-8464-3d284b1e9743
b8586b85-17e5-4235-a536-327034188259
46146f8f-0cef-4fd0-ba30-de8f11e1538e
5159420112284770
5159420112284770
5159420108364620
5159420108364620
5159420107457270
5159420103440250
5159420103440250
f068b63a-eaf8-4ae0-8a1c-aa867695b174
3b182d5a-bba0-4cf3-86d3-3009f2247639
8e2fcd68-7dca-4f37-937c-d4b532c58539
44d85b1b-bf82-4b86-9556-9c07b504bd19
5159420110587710
5159420111379550
5159420110965530
5159420112071910
5159420104001060
79048270-1574-49da-bdfe-4e08d8539af1
9cfd7938-7dce-43be-aa4f-04b306c2ac2d
897d8892-595a-422d-b178-f2fac63a08c5
5159420105035260
226fc7d8-6461-4c96-90de-0d694e84a69e
1287021a-dce3-4c74-b24b-31f47655ed7a
f0f1e8bb-0333-4739-90e5-5055a32dfb8f
f0f1e8bb-0333-4739-90e5-5055a32dfb8f
f0f1e8bb-0333-4739-90e5-5055a32dfb8f
2e37b185-427f-4971-b524-3eaa5ab843c5
2e37b185-427f-4971-b524-3eaa5ab843c5
2e37b185-427f-4971-b524-3eaa5ab843c5
2e37b185-427f-4971-b524-3eaa5ab843c5
2e37b185-427f-4971-b524-3eaa5ab843c5
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
6ff654e4-f91a-4a08-9fa6-8a513fc486a3
d2d91305-307f-4e77-89b8-92174290e5e1
d2d91305-307f-4e77-89b8-92174290e5e1
d2d91305-307f-4e77-89b8-92174290e5e1
d2d91305-307f-4e77-89b8-92174290e5e1
3a8c4660-f9b7-4b2f-8cc5-9b3fc3ffe085
3a8c4660-f9b7-4b2f-8cc5-9b3fc3ffe085
ff66b753-64b1-480e-8d7c-698f4ed1c28c
ff66b753-64b1-480e-8d7c-698f4ed1c28c
77acd305-5728-4ef9-900c-67d5ffc3d802
77acd305-5728-4ef9-900c-67d5ffc3d802
778c6cda-d844-4faa-badc-a4aa357dde78
778c6cda-d844-4faa-badc-a4aa357dde78
778c6cda-d844-4faa-badc-a4aa357dde78
b68fd490-257f-4e5d-8eec-c64b23268c7d
b68fd490-257f-4e5d-8eec-c64b23268c7d
b68fd490-257f-4e5d-8eec-c64b23268c7d
4952fb04-1122-456f-bd80-fc8615b0911b
4952fb04-1122-456f-bd80-fc8615b0911b
4952fb04-1122-456f-bd80-fc8615b0911b
d046e436-ce02-4fb0-9de2-0e9cc81ae056
d046e436-ce02-4fb0-9de2-0e9cc81ae056
d046e436-ce02-4fb0-9de2-0e9cc81ae056
ef76592c-6d4f-4fcc-9811-5bbc7616060d
ef76592c-6d4f-4fcc-9811-5bbc7616060d
ef76592c-6d4f-4fcc-9811-5bbc7616060d
ef76592c-6d4f-4fcc-9811-5bbc7616060d
ef76592c-6d4f-4fcc-9811-5bbc7616060d
a896b119-5c12-4ed1-834f-1168596c857a
a896b119-5c12-4ed1-834f-1168596c857a
6e62f0a1-a573-4e1d-b0fb-9b36c37e9499
6e62f0a1-a573-4e1d-b0fb-9b36c37e9499
98d4b47b-df9d-4d1a-a6f3-f799794fa881
98d4b47b-df9d-4d1a-a6f3-f799794fa881
98d4b47b-df9d-4d1a-a6f3-f799794fa881
4e9921ab-1ca2-4b2c-b139-5988d505b2a9
4e9921ab-1ca2-4b2c-b139-5988d505b2a9
c9a24165-dcd3-469f-82f9-c7119d00e97c
c9a24165-dcd3-469f-82f9-c7119d00e97c
636f8c81-9098-4a48-afcf-bb29fba1be14
636f8c81-9098-4a48-afcf-bb29fba1be14
636f8c81-9098-4a48-afcf-bb29fba1be14
636f8c81-9098-4a48-afcf-bb29fba1be14
26c76ccf-1a16-446b-950c-3fc22d7c2010
26c76ccf-1a16-446b-950c-3fc22d7c2010
26c76ccf-1a16-446b-950c-3fc22d7c2010
26c76ccf-1a16-446b-950c-3fc22d7c2010
26c76ccf-1a16-446b-950c-3fc22d7c2010
7bdcd237-3dea-4caf-a959-d335c9d63751
7bdcd237-3dea-4caf-a959-d335c9d63751
7bdcd237-3dea-4caf-a959-d335c9d63751
99fe4e8f-3817-4e5e-a45a-316b73e4a13d
99fe4e8f-3817-4e5e-a45a-316b73e4a13d
c12fd29f-90d6-4b16-8702-bd3971dd48cc
c12fd29f-90d6-4b16-8702-bd3971dd48cc
55dfa3b1-1514-45f2-a40f-96144110d67d
55dfa3b1-1514-45f2-a40f-96144110d67d
55dfa3b1-1514-45f2-a40f-96144110d67d
5159420108356460
5159420108356460
faf803fc-5ebd-4050-96bc-e14dd6a26354
faf803fc-5ebd-4050-96bc-e14dd6a26354
1563bd40-db23-4dd6-828f-4ce6078a5949
1563bd40-db23-4dd6-828f-4ce6078a5949
1563bd40-db23-4dd6-828f-4ce6078a5949
5372b904-8a30-48b7-9f07-23422a6a10d0
5372b904-8a30-48b7-9f07-23422a6a10d0
5159420109140600
5159420109140600
ccc6f541-3504-4734-85e2-dcaa2b9c2f69
ccc6f541-3504-4734-85e2-dcaa2b9c2f69
587993ec-5c68-4fc9-ab6c-47d3b95be88b
587993ec-5c68-4fc9-ab6c-47d3b95be88b
587993ec-5c68-4fc9-ab6c-47d3b95be88b
89b4afb5-ecd7-424e-b750-a2e833c5aa82
89b4afb5-ecd7-424e-b750-a2e833c5aa82
89b4afb5-ecd7-424e-b750-a2e833c5aa82
0d298354-b6ca-472d-91ce-a163dd93a842
0d298354-b6ca-472d-91ce-a163dd93a842
d5d5fa2b-dd70-4390-bfd9-2c7c8babe3f9
d5d5fa2b-dd70-4390-bfd9-2c7c8babe3f9
f6fe2142-d79a-422d-a415-eda6e8ce5ade
f6fe2142-d79a-422d-a415-eda6e8ce5ade
d93f41e8-8b9c-4e9b-a0c8-82c3962e579f
d93f41e8-8b9c-4e9b-a0c8-82c3962e579f
5159420112422820
5159420106283180
5159420111583220
5159420111583220
23e61d43-138a-4c42-957b-ee5dd27e0b85
5159420103337330
5159420103337330
5159420101055670
5159420107184460
5159420104737180
5159420107018810
bcac05ec-b4e1-42a2-8714-ad781fc8a643
f58a9914-2ca0-4502-bd62-b2c960261d91
5159420103805670
ca37f48f-3bdd-4ba8-93e1-8da38b8e87a8
98ffddeb-b53f-4ca9-9cc5-20f6f02c9e04
5159420105649880
1dfbed30-3604-4c47-95da-e9a0c82201d3
a34fd9c5-cb75-4c44-b33e-684740df31b1
5159420103172330
5159420103172330
5159420110968300
5159420107308920
2c9764f3-604f-4469-bc94-c292a0c2a07e
5159420110372370
5159420101819990
5159420109866700
5159420109866700
5159420106063650
5159420111957880
5159420111957880
5159420109783440
5159420100050520
5159420101995530
9994924b-8d64-4a96-83c0-627c5dd48a75
e1e286b8-2c17-4709-8cf1-17dd4e73cabe
5159420109044340
5159420105965370
ffec9e1a-4c0a-4d35-8a7f-58da181c1da6
a15b4c26-0023-423b-97cc-6594f6059d47
a15b4c26-0023-423b-97cc-6594f6059d47
a15b4c26-0023-423b-97cc-6594f6059d47
a15b4c26-0023-423b-97cc-6594f6059d47
a15b4c26-0023-423b-97cc-6594f6059d47
b2a1fda7-b68d-4ef5-9e9f-c521002d2346
b2a1fda7-b68d-4ef5-9e9f-c521002d2346
663d6295-3d31-4e12-8c7d-620b101c84db
663d6295-3d31-4e12-8c7d-620b101c84db
663d6295-3d31-4e12-8c7d-620b101c84db
663d6295-3d31-4e12-8c7d-620b101c84db
663d6295-3d31-4e12-8c7d-620b101c84db
addf034b-aa16-4df2-a6f8-19a4b7499f71
addf034b-aa16-4df2-a6f8-19a4b7499f71
addf034b-aa16-4df2-a6f8-19a4b7499f71
bd87844f-9141-49a9-8674-10723b1ac25c
bd87844f-9141-49a9-8674-10723b1ac25c
65d91c92-3c76-4d5d-9d98-a18a399eb943
65d91c92-3c76-4d5d-9d98-a18a399eb943
65d91c92-3c76-4d5d-9d98-a18a399eb943
b414c0f1-d6eb-4177-b8f0-4cc5f4b0dd10
b414c0f1-d6eb-4177-b8f0-4cc5f4b0dd10
d81b65fd-fc6e-4b93-a89a-ee2242106886
d81b65fd-fc6e-4b93-a89a-ee2242106886
849f83da-b48c-4a93-908a-5473a3f8488a
849f83da-b48c-4a93-908a-5473a3f8488a
849f83da-b48c-4a93-908a-5473a3f8488a
0d9d8691-573a-45e8-b3bf-031aa5b851f7
0d9d8691-573a-45e8-b3bf-031aa5b851f7
0d9d8691-573a-45e8-b3bf-031aa5b851f7
a9a30d7d-8580-434e-82a1-f238891efe1f
a9a30d7d-8580-434e-82a1-f238891efe1f
a9a30d7d-8580-434e-82a1-f238891efe1f
dfc3bbdd-96d8-430d-aa5e-fe82bb60d94f
dfc3bbdd-96d8-430d-aa5e-fe82bb60d94f
dfc3bbdd-96d8-430d-aa5e-fe82bb60d94f
b344ec96-3309-4747-82ed-b233dcacbed0
b344ec96-3309-4747-82ed-b233dcacbed0
a425fc44-e819-4c01-8ea2-c18ba590cf59
a425fc44-e819-4c01-8ea2-c18ba590cf59
def518e0-5f60-45fb-a61d-29ed575c5907
def518e0-5f60-45fb-a61d-29ed575c5907
629d2078-8edd-48a4-a3d1-1b3f219a38dc
629d2078-8edd-48a4-a3d1-1b3f219a38dc

In [7]:
pd.merge

,folder_name,cc_account_id,userId,context_traits_email
0,1668643200000,5159420101946752,5159420101946750,franciscomh1973@gmail.com
1,1668643200000,5159420102345053,5159420102345050,jandbharrell@gmail.com
2,1668038400000,5159420111281877,5159420111281870,jasonae@icloud.com
3,1669075200000,5159420109795797,5159420109795790,tesstaylor@msn.com
4,1668211200000,5159420101272951,5159420101272950,kvarela0704@gmail.com
...,...,...,...,...
10731,1668124800000,5159420102091244,5159420102091240,nicoledasilva69@gmail.com
10732,1669075200000,5159420104629603,5159420104629600,ann.paul.wetzel@gmail.com
10733,1669334400000,5159420100642832,5159420100642830,mikkishell67@gmail.com
10734,1669075200000,5159420101604963,5159420101604960,barbiepinkie1223@yahoo.com
10735,1668556800000,5159420102251210,5159420102251210,smudude@gmail.com

In [2]:
data = pd.read_parquet('1668988800000.parquet')

In [6]:
correction_df = pd.read_csv('braze_correction.csv')

In [62]:
len(correction_df)

10736

In [63]:
s = correction_df.duplicated()
len(s)

10736

In [23]:
data[data.userId == 5159420109617060]

Empty DataFrame
Columns: [channel, event, integrations, messageId, originalTimestamp, projectId, receivedAt, sentAt, timestamp, type, userId, version, writeKey, context_integrations_Appboy, context_integrations_name, context_integrations_version, context_library_name, context_library_version, context_protocols_sourceId, context_traits_email, properties_campaign_id, properties_campaign_name, properties_dispatch_id, properties_esp, properties_from_domain, properties_ip_pool, properties_message_variation_id, folder_name, properties_canvas_id, properties_canvas_name, properties_canvas_step_id, properties_canvas_step_name, properties_canvas_variation_id, properties_canvas_variation_name, properties_app_id, properties_platform, properties_machine_open, context_device_model, context_device_type, properties_link_url, properties_in_control_group, properties_user_agent, properties_bounce_reason, properties_conversion_behavior, properties_conversion_behavior_index, properties_subscription_group_id, properties_subscription_status, folder_time_name]
Index: []

[0 rows x 48 columns]

In [36]:
correction_df = correction_df[~correction_df.cc_account_id.isna()]

In [37]:
correction_df.cc_account_id

0        5.159420e+15
1        5.159420e+15
2        5.159420e+15
3        5.159420e+15
4        5.159420e+15
             ...
10749    5.159420e+15
10750    5.159420e+15
10751    5.159420e+15
10752    5.159420e+15
10753    5.159420e+15
Name: cc_account_id, Length: 10736, dtype: float64

In [49]:
data.userId = data.userId.astype('string')
correction_df.userId = correction_df.userId.astype('str')

In [46]:
data.userId

0    5159420104033730
0    5159420104033730
0    5159420104033730
0    5159420104033730
1    5159420103228220
           ...
0    5159420100589940
1    5159420101961330
0    5159420103635570
0    5159420107999200
0    5159420101151440
Name: userId, Length: 11258, dtype: string

In [41]:
correction_df.userId

0        5159420105037170
1        5159420103346150
2        5159420103383300
3        5159420107327130
4        5159420104544510
               ...
10749    5159420107442780
10750    5159420102151680
10751    5159420100168230
10752    5159420106083150
10753    5159420101003910
Name: userId, Length: 10736, dtype: int64

In [61]:
pd.remove_duplicates(correction_df)

AttributeError: module 'pandas' has no attribute 'remove_duplicates'

In [72]:
len(data.merge(correction_df, on='userId'))

16989

In [71]:
len(data)

11258

In [87]:
correction_df[~correction_df[['cc_account_id','userId']].duplicated()]

         folder_name  cc_account_id            userId
0      1669334400000   5.159420e+15  5159420105037170
1      1668988800000   5.159420e+15  5159420103346150
2      1668988800000   5.159420e+15  5159420103383300
3      1668643200000   5.159420e+15  5159420107327130
4      1668124800000   5.159420e+15  5159420104544510
...              ...            ...               ...
10740  1668124800000   5.159420e+15  5159420105325560
10743  1668556800000   5.159420e+15  5159420108948650
10744  1668556800000   5.159420e+15  5159420100983780
10748  1668556800000   5.159420e+15  5159420102450890
10750  1668988800000   5.159420e+15  5159420102151680

[6967 rows x 3 columns]

In [ ]:
correction_df5159420105037170